// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtTqcWQ_YmqEt4SkFO8YZUEolgrsMg4y0',
    appId: '1:612099708143:web:2830cdaae0db312f0c371a',
    messagingSenderId: '612099708143',
    projectId: 'todo-c5b85',
    authDomain: 'todo-c5b85.firebaseapp.com',
    storageBucket: 'todo-c5b85.appspot.com',
    measurementId: 'G-NEE79E3JGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Xbh-KVgCHhQL_gOO3HkBw6iFg0luNLM',
    appId: '1:612099708143:android:545942d760016eed0c371a',
    messagingSenderId: '612099708143',
    projectId: 'todo-c5b85',
    storageBucket: 'todo-c5b85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlyqgOg2WfGgC161TUPSO1rgi9DUq8IDA',
    appId: '1:612099708143:ios:48a604eea9b1c73d0c371a',
    messagingSenderId: '612099708143',
    projectId: 'todo-c5b85',
    storageBucket: 'todo-c5b85.appspot.com',
    iosBundleId: 'com.example.todoWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtTqcWQ_YmqEt4SkFO8YZUEolgrsMg4y0',
    appId: '1:612099708143:web:7f16a0a1b98ef0500c371a',
    messagingSenderId: '612099708143',
    projectId: 'todo-c5b85',
    authDomain: 'todo-c5b85.firebaseapp.com',
    storageBucket: 'todo-c5b85.appspot.com',
    measurementId: 'G-HD8WN4X2DB',
  );

}